Parse macro parameters using duckdb dialect
These kinds of macros would fail when the macro is used:
```
CREATE MACRO m(mp MAP(VARCHAR, INTEGER)) AS (mp['a'])
CREATE MACRO m(st STRUCT(i INTEGER)) AS (st.i)
CREATE MACRO m(l VARCHAR[]) AS (len(l))
```

This one would default to the string "NULL" instead of NULL.
```
CREATE MACRO m(s VARCHAR := NULL::VARCHAR) AS (s IS NULL)
```

These would fail on attach:
```
CREATE MACRO m(d DATE := NULL::DATE) AS (d IS NULL)
   Failed to cast value: invalid date field format: "NULL"
CREATE MACRO m(l VARCHAR[] := NULL::VARCHAR[]) AS (l IS NULL)
   FATAL Error: ... database has been invalidated
```

This works by changing `parameter_type` for all macros back to what
3035a798 had so we have the inner types of things like STRUCT and LIST.

If there's a default value it always sets `default_value_type` to
`expression` and uses the expression parser on it. Older rows it parses
as constants using the type already in there.

For < 1.1-dev1 versioned catalogs it fails these cases with an error
message.

Because it handles expression-valued defaults, these also work now:
```
CREATE MACRO m(st STRUCT(i INTEGER) := {'i': 1}) AS (st.i)
CREATE MACRO m(l VARCHAR[] := ['x', 'y']) AS (len(l))
```